name: human_calib
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # --- Core Environment ---
  - python=3.8
  - pip
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision=0.14.1
  - pytorch::pytorch-cuda=11.7 # Assure la compatibilité CUDA pour PyTorch

  # --- Scientific & Data Handling ---
  - numpy
  - scipy
  - pandas
  - pyyaml

  # --- Video & Visualization ---
  - matplotlib
  - tqdm
  - ffmpeg

  # --- Pip Dependencies ---
  - pip:
    # --- 2D Pose Estimation (RTMPose) ---
    - rtmlib
    - onnxruntime-gpu # Inference motor for RTMPose, GPU version

    # --- Calibration & 3D ---
    - opencv-contrib-python==4.7.0.72
    - numba
    - pycalib-simple

    # --- Utilities ---
    - tomli # To open config .toml (for Python 3.8 to 3.10)
    - nvgpu-py # For automatic selection GPU
    - imageio==2.22.2
    - networkx
    - tabulate
    - termcolor
    - portalocker
    - ninja